PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    salt CHAR(64) NOT NULL,
    hashed_password CHAR(64) NOT NULL,
    recovery_key CHAR(64) NOT NULL,
    created_time INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS user_sessions (
    id INTEGER PRIMARY KEY,
    user INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    session_key CHAR(64) NOT NULL UNIQUE,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    start_time INTEGER NOT NULL,
    end_time INTEGER
);

CREATE TABLE IF NOT EXISTS media (
    id INTEGER PRIMARY KEY,
    user INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    relative_path TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    hashed_value CHAR(64) NOT NULL,
    UNIQUE(user, hashed_value)
);

CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY,
    user INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    title TEXT
);

CREATE TABLE IF NOT EXISTS scenes (
    id INTEGER PRIMARY KEY,
    project INTEGER REFERENCES projects(id) ON DELETE CASCADE NOT NULL,
    title TEXT
);

CREATE TABLE IF NOT EXISTS layers (
    id INTEGER PRIMARY KEY,
    scene INTEGER REFERENCES scenes(id) ON DELETE CASCADE NOT NULL,
    title TEXT,
    z INTEGER
);

CREATE TABLE IF NOT EXISTS sprites (
    id INTEGER PRIMARY KEY,
    layer INTEGER REFERENCES layers(id) ON DELETE CASCADE NOT NULL,
    media INTEGER REFERENCES media(id) ON DELETE SET NULL NOT NULL,
    x REAL,
    y REAL,
    w REAL,
    h REAL
);
